import { 
  BookOpen, 
  MessageSquare, 
  Video,
  Lightbulb,
  Code,
  FileText,
  Award
} from 'lucide-react';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { cn } from '@/lib/utils';

const features = [
  {
    icon: BookOpen,
    title: 'Quiz Arena',
    description: 'Test your knowledge across various domains, subjects, and topics with interactive quizzes at different difficulty levels.',
    color: 'bg-blue-100 text-blue-700',
  },
  {
    icon: MessageSquare,
    title: 'AI Assistant',
    description: 'Get instant help with coding problems, summaries, and engage with our AI-powered chatbot in multiple languages.',
    color: 'bg-thinksparkPurple-100 text-thinksparkPurple-500',
  },
  {
    icon: Video,
    title: 'Video Classes',
    description: 'Join live interactive video classes with real-time monitoring and engagement with experienced teachers.',
    color: 'bg-red-100 text-red-700',
  },
  {
    icon: Lightbulb,
    title: 'Innovation Hub',
    description: 'Showcase your tech solutions and get feedback from peers and teachers to foster a creative community.',
    color: 'bg-amber-100 text-amber-700',
  },
  {
    icon: Code,
    title: 'Story Mode',
    description: 'Learn concepts through engaging stories generated by AI, followed by quizzes to test your understanding.',
    color: 'bg-green-100 text-green-700',
  },
  {
    icon: Code,
    title: 'Interview Prep',
    description: 'Sharpen your Data Structures and Algorithms skills with GeeksforGeeks-style interview questions, timed quizzes, and instant AI feedback.',
    color: 'bg-green-100 text-green-700',
  },
  {
    icon: Award,
    title: 'Career Advisor & Resume Builder',
    description: 'Get career advice based on your learning activity and build a professional resume tailored to your interests, all powered by AI.',
    color: 'bg-indigo-100 text-indigo-700',
  }
];

const FeaturesSection = () => {
  return (
    <section className="py-16 bg-white">
      <div className="container mx-auto px-4">
        <div className="text-center mb-16">
          <h2 className="text-3xl md:text-4xl font-bold mb-4">
            Comprehensive Learning Features
          </h2>
          <p className="text-xl text-gray-600 max-w-2xl mx-auto">
            Our platform combines multiple learning approaches to ensure a complete and engaging educational experience.
          </p>
        </div>
        
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
          {features.map((feature, index) => (
            <Card 
              key={index} 
              className="border border-gray-100 shadow-sm hover:shadow-md transition-shadow card-hover"
            >
              <CardHeader>
                <div className={cn("w-12 h-12 rounded-lg flex items-center justify-center mb-4", feature.color)}>
                  <feature.icon className="h-6 w-6" />
                </div>
                <CardTitle>{feature.title}</CardTitle>
              </CardHeader>
              <CardContent>
                <CardDescription className="text-base">{feature.description}</CardDescription>
              </CardContent>
            </Card>
          ))}
        </div>
        
        <div className="mt-16 text-center">
          <div className="inline-flex items-center p-1 rounded-full bg-thinksparkPurple-100 text-thinksparkPurple-500 text-sm font-medium mb-6">
            <span className="px-3 py-1 rounded-full bg-white shadow-sm">
              AI-Powered
            </span>
            <span className="px-3">Real-time Interaction</span>
          </div>
          
          <h3 className="text-2xl md:text-3xl font-bold mb-6">
            Powered by Advanced Artificial Intelligence
          </h3>
          
          <p className="text-gray-600 max-w-2xl mx-auto mb-8">
            Our platform leverages the latest in AI technology, including OpenRouter for chatbots, voice processing for accessibility, and YOLOv8 for real-time video analysis during classes.
          </p>
          
          <div className="bg-gradient-to-r from-thinksparkPurple-200 to-thinksparkPurple-100 p-6 rounded-xl max-w-4xl mx-auto">
            <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
              <div className="bg-white p-4 rounded-lg shadow-sm">
                <div className="font-bold text-thinksparkPurple-400 mb-2">Natural Language</div>
                <p className="text-sm text-gray-600">Understand and respond to questions in natural language with context awareness</p>
              </div>
              <div className="bg-white p-4 rounded-lg shadow-sm">
                <div className="font-bold text-thinksparkPurple-400 mb-2">Computer Vision</div>
                <p className="text-sm text-gray-600">Real-time monitoring and object detection during video classes</p>
              </div>
              <div className="bg-white p-4 rounded-lg shadow-sm">
                <div className="font-bold text-thinksparkPurple-400 mb-2">Voice Recognition</div>
                <p className="text-sm text-gray-600">Convert speech to text and back for a natural learning experience</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};

export default FeaturesSection;
