// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pxezfsefrohdlwtoitis.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB4ZXpmc2Vmcm9oZGx3dG9pdGlzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4NjI4NTEsImV4cCI6MjA2MjQzODg1MX0.R6nUo5Byb9lhiLiD5S-fecagwXDMexGtSQIcMIyDuHM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);